CREATE TABLE "Clients"
(
    "Id"         bigint,
    "ClientName" varchar(200)
);

insert into "Clients" ("Id", "ClientName")
values (1, 'Vasya'),
       (2, 'Petya'),
       (3, 'Dima'),
       (4, 'Kolya'),
       (5, 'Sasha'),
       (6, 'Nastya')
;

CREATE TABLE "ClientContacts"
(
    "Id"           bigint GENERATED BY DEFAULT AS IDENTITY,
    "ClientId"     bigint,
    "ContactType"  varchar(200),
    "ContactValue" varchar(200)
);

insert into "ClientContacts" ("ClientId", "ContactType", "ContactValue")
values (1, 'email', 'Vasya@mail.ru'),
       (1, 'phone', '1111111'),
       (1, 'telegram', '@vasya'),

       (2, 'email', 'Petya@mail.ru'),

       (3, 'email', 'Dima@mail.ru'),
       (3, 'telegram', '@dima'),

       (4, 'phone', '4444444'),

       (5, 'email', 'Sasha@mail.ru'),
       (5, 'telegram', '@sasha'),
       (5, 'phone', '5555555'),

       (6, 'telegram', '@Nastya');


-- 1 Написать запрос, который возвращает наименование клиентов и кол-во контактов клиентов

select
    c."ClientName",
    count(cc.*) as "Contacts Count"
from "Clients" C join "ClientContacts" cc on c."Id" = cc."ClientId"
group by c."ClientName";

-- 2 Написать запрос, который возвращает список клиентов, у которых есть более 2 контактов

select
    c."ClientName"
from "Clients" C join "ClientContacts" cc on c."Id" = cc."ClientId"
group by c."ClientName"
having count(cc.*) > 2;